### ISSUE TITLE
System.Security.Cryptography.CryptographicException: 'ASN1 corrupted data.'

### ISSUE THREAD

**Issue by numan236** [krstan4o/borica#2]
hello
when i try to read privatekey i get this error

 byte[] der = Convert.FromBase64String(base64);
                    RSA rsa = RSA.Create();
                    rsa.ImportRSAPrivateKey(der, out _);
                    return rsa;

System.Security.Cryptography.CryptographicException: 'ASN1 corrupted data.'

**Comment by krstan4o** [comment]
Hi

Can you provide some test .pem certificate (private key) so we can test this.

**Comment by numan236** [comment]
Hi
can you give me email to send pem and private key

**Comment by krstan4o** [comment]
krstan4o@yahoo.com

Thanks

**Comment by krstan4o** [comment]
I have added additional support for reading openssl formated - private rsa des encripted files.

Can you try it now. => https://www.nuget.org/packages/Borica (1.0.51)

Best regards.

**Comment by numan236** [comment]
Yes it is working 
thank you
